# Generated by Django 3.2 on 2021-11-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullnamee',
            new_name='fullname',
        ),
    ]
