# Generated by Django 3.2 on 2021-11-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeregister', '0002_rename_fullnamee_employee_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
